name: app_widgetbook
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  widgetbook: ^3.0.0-beta.6
  core:
    path: ../packages/core
  auth:
    path: ../packages/auth
  app:
    path: ../packages/app
  widgetbook_annotation: ^3.0.0-beta.2
  timeago: ^3.3.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
  widgetbook_generator: ^3.0.0-beta.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
