name: core
description: Core components for Widgetbook Demo App
version: 0.1.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  timeago: ^3.3.0
  video_player: ^2.5.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0+1

flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: TwitterIcons
      fonts:
        - asset: assets/fonts/TwitterIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300