name: core
description: Core components for Widgetbook Demo App
version: 0.1.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  widgetbook_annotation: ^2.1.0
  video_player: ^2.4.7
  timeago: ^3.3.0
  cached_network_image: ^3.2.2
  flutter_markdown: ^0.6.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  widgetbook: ^2.4.1
  widgetbook_generator: ^2.4.1

flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: TwitterIcons
      fonts:
        - asset: assets/fonts/TwitterIcons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300