name: Build
on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging
      - main
jobs:
  build:
    defaults:
      run:
        working-directory: ./app_widgetbook

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build Website
        run: flutter build web -t lib/main.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Upload Widgetbook
        run: |
          widgetbook \
                --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }} \
                --repository \
                $GITHUB_REPOSITORY \
                --actor \
                $GITHUB_ACTOR \
                --branch \
                $GITHUB_HEAD_REF \
                --pr ${{ github.event.number }} \
                --github-token ${{ secrets.GITHUB_TOKEN }}
